// automatically generated by the FlatBuffers compiler, do not modify

import { IdentifyC } from '../go-fish/identify-c.js';
import { StartGameC } from '../go-fish/start-game-c.js';


export enum Cmsg {
  NONE = 0,
  IdentifyC = 1,
  StartGameC = 2
}

export function unionToCmsg(
  type: Cmsg,
  accessor: (obj:IdentifyC|StartGameC) => IdentifyC|StartGameC|null
): IdentifyC|StartGameC|null {
  switch(Cmsg[type]) {
    case 'NONE': return null; 
    case 'IdentifyC': return accessor(new IdentifyC())! as IdentifyC;
    case 'StartGameC': return accessor(new StartGameC())! as StartGameC;
    default: return null;
  }
}

export function unionListToCmsg(
  type: Cmsg, 
  accessor: (index: number, obj:IdentifyC|StartGameC) => IdentifyC|StartGameC|null, 
  index: number
): IdentifyC|StartGameC|null {
  switch(Cmsg[type]) {
    case 'NONE': return null; 
    case 'IdentifyC': return accessor(index, new IdentifyC())! as IdentifyC;
    case 'StartGameC': return accessor(index, new StartGameC())! as StartGameC;
    default: return null;
  }
}
