// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Create {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Create {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCreate(bb:flatbuffers.ByteBuffer, obj?:Create):Create {
  return (obj || new Create()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCreate(bb:flatbuffers.ByteBuffer, obj?:Create):Create {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Create()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startCreate(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endCreate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCreate(builder:flatbuffers.Builder):flatbuffers.Offset {
  Create.startCreate(builder);
  return Create.endCreate(builder);
}
}
