// automatically generated by the FlatBuffers compiler, do not modify

import { Create } from '../go-fish/create.js';
import { Join } from '../go-fish/join.js';


export enum GameRef {
  NONE = 0,
  Create = 1,
  Join = 2
}

export function unionToGameRef(
  type: GameRef,
  accessor: (obj:Create|Join) => Create|Join|null
): Create|Join|null {
  switch(GameRef[type]) {
    case 'NONE': return null; 
    case 'Create': return accessor(new Create())! as Create;
    case 'Join': return accessor(new Join())! as Join;
    default: return null;
  }
}

export function unionListToGameRef(
  type: GameRef, 
  accessor: (index: number, obj:Create|Join) => Create|Join|null, 
  index: number
): Create|Join|null {
  switch(GameRef[type]) {
    case 'NONE': return null; 
    case 'Create': return accessor(index, new Create())! as Create;
    case 'Join': return accessor(index, new Join())! as Join;
    default: return null;
  }
}
