// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class GameCreationResponseS {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GameCreationResponseS {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGameCreationResponseS(bb:flatbuffers.ByteBuffer, obj?:GameCreationResponseS):GameCreationResponseS {
  return (obj || new GameCreationResponseS()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGameCreationResponseS(bb:flatbuffers.ByteBuffer, obj?:GameCreationResponseS):GameCreationResponseS {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GameCreationResponseS()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startGameCreationResponseS(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static endGameCreationResponseS(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGameCreationResponseS(builder:flatbuffers.Builder, id:number):flatbuffers.Offset {
  GameCreationResponseS.startGameCreationResponseS(builder);
  GameCreationResponseS.addId(builder, id);
  return GameCreationResponseS.endGameCreationResponseS(builder);
}
}
