// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Join {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Join {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsJoin(bb:flatbuffers.ByteBuffer, obj?:Join):Join {
  return (obj || new Join()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsJoin(bb:flatbuffers.ByteBuffer, obj?:Join):Join {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Join()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startJoin(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static endJoin(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createJoin(builder:flatbuffers.Builder, id:number):flatbuffers.Offset {
  Join.startJoin(builder);
  Join.addId(builder, id);
  return Join.endJoin(builder);
}
}
