// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class StartGameC {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StartGameC {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStartGameC(bb:flatbuffers.ByteBuffer, obj?:StartGameC):StartGameC {
  return (obj || new StartGameC()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStartGameC(bb:flatbuffers.ByteBuffer, obj?:StartGameC):StartGameC {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StartGameC()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startStartGameC(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endStartGameC(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStartGameC(builder:flatbuffers.Builder):flatbuffers.Offset {
  StartGameC.startStartGameC(builder);
  return StartGameC.endStartGameC(builder);
}
}
