// automatically generated by the FlatBuffers compiler, do not modify

export { Cmsg } from './go-fish/cmsg.js';
export { CmsgTable } from './go-fish/cmsg-table.js';
export { Create } from './go-fish/create.js';
export { ErrorS } from './go-fish/error-s.js';
export { GameCreationResponseS } from './go-fish/game-creation-response-s.js';
export { GameRef } from './go-fish/game-ref.js';
export { IdentifyC } from './go-fish/identify-c.js';
export { Join } from './go-fish/join.js';
export { Smsg } from './go-fish/smsg.js';
export { SmsgTable } from './go-fish/smsg-table.js';
export { StartGameC } from './go-fish/start-game-c.js';
